workflows:
  ios-sideload-workflow:
    name: iOS Sideload Workflow
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Turbo Build
        script: |
          # 1. Восстанавливаем и подтягиваем пакеты
          flutter create --platforms=ios --org com.coolmag .
          flutter pub get
          
          # 2. Устанавливаем поды
          cd ios && pod install && cd ..
          
          # 3. Собираем самую быструю Debug версию
          flutter build ios --debug --no-codesign
          
          # 4. Упаковываем в IPA
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/debug-iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa && zip -r Runner.ipa Payload
    artifacts:
      - build/ios/ipa/Runner.ipa
